//Auth actions
export const SET_AUTH_LOADER = "SET_AUTH_LOADER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const SET_TOKEN = "SET_TOKEN";
export const SET_TOTAL_BALANCE = "SET_TOTAL_BALANCE";
export const SET_CONTACTS = "SET_CONTACTS";
export const SET_VEDPAY_USERS = "SET_VEDPAY_USERS";

//Card actions
export const SET_CARD_LOADER = "SET_CARD_LOADER";
export const ADD_CARD = "ADD_CARD";
export const SET_CARD_LIST = "SET_CARD_LIST";

// In actions
export const SET_IN_LOADER = "SET_IN_LOADER";
export const SET_IN_AMOUNT = "SET_IN_AMOUNT";

//Transaction actions
export const SET_TRANSACTION_LOADER = "SET_TRANSACTION_LOADER";
export const SET_TRANSACTION_DETAILS = "SET_TRANSACTION_DETAILS";
export const SET_CONTACT_TRANSACTION = "SET_CONTACT_TRANSACTION";
export const SET_GLOBAL_TRANSACTION = "SET_GLOBAL_TRANSACTION";

//Out actions
export const SET_OUT_LOADER = "SET_OUT_LOADER";
export const SET_SELECTED_CONTACT = "SET_SELECTED_CONTACT";
export const SET_OUT_AMOUNT = "SET_OUT_AMOUNT";

// Message
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
